name: face_detection_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.4
  image: ^4.1.3
  google_ml_kit: ^0.16.3
  google_mlkit_face_detection: ^0.9.0
  tflite_flutter: ^0.10.4
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  lottie: ^2.7.0
  google_mlkit_commons: ^0.6.1
  camera: ^0.10.5+8
  rive: ^0.12.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.14.0
  fluttertoast: ^8.2.4

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/face_loading_2.json
    - assets/images/face_loading_3.json
    - assets/images/face_loading_4.json
    - assets/images/face_loading.json
    - assets/images/face_r.json
    - assets/images/homescreen.json
    - assets/images/faceregbasarili.json
    - assets/model/mobilefacenet.tflite
    - assets/model/mobilefacenett.tflite
    - assets/model/facenet.tflite

